file = open("sample.txt", "r")
data = file.read()
lines = len(data.split("\n"))
words = len(data.split())
characters = len(data)
print("Number of Lines:", lines)
print("Number of Words:", words)
print("Number of Characters:", characters)
file.close()